<a href="https://colab.research.google.com/github/Badu1230/Badu1230/blob/main/ETL_Python_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [4]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [7]:
data.shape

(17000, 9)

In [8]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
16995    False
16996    False
16997    False
16998    False
16999    False
Length: 17000, dtype: bool

In [9]:
data.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [12]:
sample_data = pd.read_csv("/content/sample_data/mnist_test.csv")

In [13]:
sample_data.head()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
sample_data.shape

(9999, 785)

In [15]:
sample_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 785 entries, 7 to 0.667
dtypes: int64(785)
memory usage: 59.9 MB

In [18]:
sample_data.tail()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
9994,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9995,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
sample_data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9994    False
9995    False
9996    False
9997    False
9998    False
Length: 9999, dtype: bool

In [3]:
order = pd.read_excel("/content/H+ Sport Orders.xlsx")

In [4]:
order.head()

,OrderID,Date,TotalDue,Status,CustomerID,SalespersonID,CustomersComment,SalespersonsComment
0,1000,05/14/2016,$140.91,paid,413,130,NaN,NaN
1,1001,07/31/2016,$105.32,returned,128,102,NaN,NaN
2,1002,07/09/2016,$217.30,past due,791,115,NaN,NaN
3,1003,04/04/2016,$281.39,paid,974,139,NaN,NaN
4,1004,02/16/2016,$254.76,paid,866,102,NaN,NaN

In [5]:
customers = pd.read_excel("/content/H+ Sport Orders.xlsx")

In [6]:
customers.head()

,OrderID,Date,TotalDue,Status,CustomerID,SalespersonID,CustomersComment,SalespersonsComment
0,1000,05/14/2016,$140.91,paid,413,130,NaN,NaN
1,1001,07/31/2016,$105.32,returned,128,102,NaN,NaN
2,1002,07/09/2016,$217.30,past due,791,115,NaN,NaN
3,1003,04/04/2016,$281.39,paid,974,139,NaN,NaN
4,1004,02/16/2016,$254.76,paid,866,102,NaN,NaN

In [13]:
customers = pd.read_excel("/content/H+ Sport Customers.xlsx",sheet_name="data")

In [14]:
customers.head()

,CustomerID,FirstName,LastName,Email,Phone,Address,City,State,Zipcode
0,100,Carol,Shaw,cshaw0@mlb.com,(206)804-8771,8157 Longview Court,Seattle,WA,98121
1,101,Elizabeth,Carr,ecarr1@oracle.com,(512)187-2507,3934 Petterle Trail,Austin,TX,78732
2,102,Ernest,Ramos,eramos2@plala.or.jp,(816)540-4257,8699 Clarendon Terrace,Kansas City,MO,64199
3,103,Jane,Carter,jcarter3@harvard.edu,(214)839-0542,2830 Novick Lane,Irving,TX,75037
4,104,Martha,Cooper,mcooper4@go.com,(727)235-5696,4537 Hoard Lane,Tampa,FL,33625

In [15]:
customers.columns

Index(['CustomerID', 'FirstName', 'LastName', 'Email', 'Phone', 'Address',
       'City', 'State', 'Zipcode'],
      dtype='object')

In [16]:
columns_to_check = ['Email', 'Phone','FirstName', 'LastName']

In [22]:
duplicates = customers[customers.duplicated(columns_to_check)]

In [20]:
duplicates

,CustomerID,FirstName,LastName,Email,Phone,Address,City,State,Zipcode
1000,1100,Chris,Moreno,cmorenond@mac.com,(907)709-6086,8740 Oak Valley Park,Fairbanks,AK,99790
1001,1101,Gerald,Green,ggreenne@wisc.edu,(203)541-4782,242 Eastlawn Drive,New Haven,CT,6510
1002,1102,Johnny,Ruiz,jruiznf@nba.com,(202)731-4171,70917 Meadow Valley Crossing,Washington,DC,20337
1003,1103,Carlos,Morales,cmoralesng@ed.gov,(517)792-4134,8 Jay Way,Lansing,MI,48956
1004,1104,Gloria,Ramos,gramosnh@xing.com,(646)144-6692,32091 Ryan Street,New York City,NY,10110
1005,1105,Lawrence,Sanchez,lsanchezni@prlog.org,(415)283-9050,07 Ronald Regan Center,San Francisco,CA,94164
1006,1106,Philip,Hayes,phayesnj@adobe.com,(510)315-1807,76 Transport Crossing,Oakland,CA,94622
1007,1107,George,Ortiz,gortiznk@dropbox.com,(508)876-5965,66703 Summerview Lane,Boston,MA,2119
1008,1108,Lois,Andrews,landrewsnl@tripadvisor.com,(915)181-3084,164 Summer Ridge Point,El Paso,TX,88530
1009,1109,Russell,Lawson,rlawsonnm@ebay.com,(979)278-7081,1862 Hoffman Terrace,College Station,TX,77844
1010,1110,Richard,George,rgeorgenn@usda.gov,(614)750-2828,4 Doe Crossing Parkway,Columbus,OH,43226
1011,1111,Cheryl,Moore,cmooreno@networksolutions.com,(253)648-0305,2849 Badeau Trail,Tacoma,WA,98411
1012,1112,Sarah,Sims,ssimsnp@issuu.com,(619)409-5898,2386 Springs Park,San Diego,CA,92191
1013,1113,Lori,Little,llittlenq@alibaba.com,(702)579-9171,46474 Cambridge Lane,Las Vegas,NV,89105
1014,1114,Louise,Morrison,lmorrisonrr@nifty.com,(786)955-3070,6 Donald Junction,Miami,FL,33147
1015,1115,Chris,Moreno,cmorenond@mac.com,(907)709-6086,8740 Oak Valley Park,Fairbanks,AK,99790
1016,1116,Gerald,Green,ggreenne@wisc.edu,(203)541-4782,242 Eastlawn Drive,New Haven,CT,6510
1017,1117,Johnny,Ruiz,jruiznf@nba.com,(202)731-4171,70917 Meadow Valley Crossing,Washington,DC,20337
1018,1118,Carlos,Morales,cmoralesng@ed.gov,(517)792-4134,8 Jay Way,Lansing,MI,48956
1019,1119,Gloria,Ramos,gramosnh@xing.com,(646)144-6692,32091 Ryan Street,New York City,NY,10110
1020,1120,Lawrence,Sanchez,lsanchezni@prlog.org,(415)283-9050,07 Ronald Regan Center,San Francisco,CA,94164
1021,1121,Philip,Hayes,phayesnj@adobe.com,(510)315-1807,76 Transport Crossing,Oakland,CA,94622
1022,1122,George,Ortiz,gortiznk@dropbox.com,(508)876-5965,66703 Summerview Lane,Boston,MA,2119
1023,1123,Lois,Andrews,landrewsnl@tripadvisor.com,(915)181-3084,164 Summer Ridge Point,El Paso,TX,88530
1024,1124,Russell,Lawson,rlawsonnm@ebay.com,(979)278-7081,1862 Hoffman Terrace,College Station,TX,77844
1025,1125,Richard,George,rgeorgenn@usda.gov,(614)750-2828,4 Doe Crossing Parkway,Columbus,OH,43226
1026,1126,Cheryl,Moore,cmooreno@networksolutions.com,(253)648-0305,2849 Badeau Trail,Tacoma,WA,98411
1027,1127,Sarah,Sims,ssimsnp@issuu.com,(619)409-5898,2386 Springs Park,San Diego,CA,92191
1028,1128,Lori,Little,llittlenq@alibaba.com,(702)579-9171,46474 Cambridge Lane,Las Vegas,NV,89105

In [23]:
duplicates.shape

(29, 9)

In [24]:
customers = customers[customers.duplicated(columns_to_check, keep="first")]

In [26]:
customers.isnull().sum()

CustomerID    0
FirstName     0
LastName      0
Email         0
Phone         0
Address       0
City          0
State         0
Zipcode       0
dtype: int64

In [46]:
employees = pd.read_excel("/content/H+ Sport Employees.xlsx",sheet_name = "Employees-Table")

In [47]:
employees.head()

,Employee Name,Building,Department,Status,Hire Date,Month,Years,Benefits,Salary,Job Rating,New Salary,Tax Rate,2.91%
0,"Page, Lisa",West,ADC,Full Time,1999-01-11,Jan,25,DMR,24550,1,NaN,NaN,NaN
1,"Taylor, Hector",West,ADC,Half-Time,2011-02-21,Feb,12,DM,26795,4,NaN,NaN,NaN
2,"Dawson, Jonathan",West,ADC,Contract,2007-03-06,Mar,16,NaN,42540,5,NaN,NaN,NaN
3,"Duran, Brian",Taft,ADC,Hourly,2012-08-30,Aug,11,NaN,35680,2,NaN,NaN,NaN
4,"Weber, Larry",Watson,ADC,Full Time,2007-12-31,Dec,16,M,72830,2,NaN,NaN,NaN

In [48]:
employees.isnull().sum()

Employee Name      0
Building           0
Department         0
Status             0
Hire Date          0
Month              0
Years              0
Benefits         247
Salary             0
Job Rating         0
New Salary       741
Tax Rate         741
2.91%            741
dtype: int64

In [49]:
employees.shape

(741, 13)

In [50]:
employees.columns

Index(['Employee Name', 'Building', 'Department', 'Status', 'Hire Date',
       'Month', 'Years', 'Benefits', 'Salary', 'Job Rating', 'New Salary',
       'Tax Rate', '2.91%'],
      dtype='object')

In [51]:
employees_remove_columns = ['Job Rating','New Salary','Tax Rate', '2.91%']

In [53]:
employees = employees.drop(columns=employees_remove_columns)

In [54]:
employees

,Employee Name,Building,Department,Status,Hire Date,Month,Years,Benefits,Salary
0,"Page, Lisa",West,ADC,Full Time,1999-01-11,Jan,25,DMR,24550
1,"Taylor, Hector",West,ADC,Half-Time,2011-02-21,Feb,12,DM,26795
2,"Dawson, Jonathan",West,ADC,Contract,2007-03-06,Mar,16,NaN,42540
3,"Duran, Brian",Taft,ADC,Hourly,2012-08-30,Aug,11,NaN,35680
4,"Weber, Larry",Watson,ADC,Full Time,2007-12-31,Dec,16,M,72830
...,...,...,...,...,...,...,...,...,...
736,"Olsen, Ewan",North,Research/Development,Contract,2007-02-03,Feb,16,NaN,60760
737,"Green, Kim",Watson,Research/Development,Half-Time,2000-02-01,Feb,23,DMR,31250
738,"Bradshaw, Sheryl",North,Research/Development,Contract,2008-07-10,Jul,15,NaN,64720
739,"Riley, David",Taft,Research/Development,Full Time,2010-07-25,Jul,13,DMR,46680
740,"Flynn, Melissa",Watson,Research/Development,Hourly,2010-12-31,Dec,13,NaN,19044

In [55]:
employees.columns

Index(['Employee Name', 'Building', 'Department', 'Status', 'Hire Date',
       'Month', 'Years', 'Benefits', 'Salary'],
      dtype='object')